project_id = "aczeggpaeiqpexxacqkr"

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.notify-admin]
enabled = true
verify_jwt = true
import_map = "./functions/notify-admin/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notify-admin/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notify-admin/*.html" ]
